### ISSUE TITLE
🐛 Not all history is saved to CSV

### ISSUE THREAD

**Issue by DonTodt** [caret-collective/watch-history-exporter-for-amazon-prime-video#2]
### Are you sure this is a new issue?

- [X] I have read the usage instructions
- [X] I have read the FAQ
- [X] I have searched for existing issues

### Operating System

OSX 15.1.1

### Browser

Chrome 131.0.6778.108

### What is the issue?

I have a watch history which goes back to March 2014.
When I run the script, it's fetching my titles and stores the result into a csv. So far so good..

When I look into the CSV, I see that only my history until mid Oct 2023 gets exported (around 143 records).
When I re-run the script, the same results are created.

I tried to manually scroll to the bottom of the page and then run the script. I see the complete history printed in the console, but the CSV still only contains the first 143 movies/series.

**Comment by jerboa88** [comment]
Hi @DonTodt.

Can you open the CSV file in a text editor and show me what the last 2 rows look like? 

What do these movies/shows look like on the site? If you could add a screenshot, that would be ideal.

I suspect there are some special characters in the movie/episode name that are causing an issue.

**Comment by jerboa88** [comment]
@DonTodt This should be fixed now, so I'm going to close the issue. If you still have problems, send the above info and I'll look into it.

**Comment by jerboa88** [comment]
Fixed in 514af251eb5fc39f286bba6d45b01f21d1f40e20
